export interface IEmployeeTable {
  id?: number,
  email?: string,
  email_canonical?: string,
  selfDiabetes?: boolean,
  selfHyperTension?: boolean,
  userId?: number,
  firstName?: string,
  lastName?: string,
  birthday?: Date,
  gender?: string,
  phoneNumber?:string,
  companyEmployeeId?: number,
  companyJobTitle?: string,
  pksfAgentId?: number,
  height?: number,
  weight?: number,
  approximateBirthday?: Date,
  address?: {
    id?: number,
    street?: string,
    region?: string,
    city?: string,
    postCode?: string,
    districtStr?: string,
    countryCode?: string
  },
  permanentAddress?: string,
  diabetic?: boolean,
  familyDiabetes?: boolean,
  familyHyperTension?: boolean,
  hasCardioVascularDisease?: boolean,
  hadStroke?: boolean,
  hasCancer?: boolean,
  hasCopd?: boolean,
  hasHealthCard?: boolean,
  bloodGroup?: string,
  countOfTeeth?: number,
  additionalNote?: string,
  disability?: string,
  nationalId?: number,
  organization?: string,
  hasElectricity?: boolean,
  dateOfDeath?: Date,
  dateOfConception?:Date,
  healthCardIssueDate?: Date,
  educationQualification?: string,
  userAdult?: true,
  occupation?: string,
  pregnant?: boolean,
  disable?: boolean,
  dead?: boolean,
  ageInMonths?: number,
  name?: string
}
